@include('traveller.layouts.header')
@include('traveller.layouts.sidebar')
@include('traveller.layouts.navbar')
@yield('content')
@include('traveller.layouts.script')
@include('traveller.layouts.footer')
